use tiendaRopa;
SELECT * FROM usuario;
SELECT * FROM carrito;
SELECT * FROM roles;
SELECT * FROM user_roles;
SELECT * FROM producto;
SELECT * FROM pedido;
SELECT * FROM realizarPedido;
SELECT * FROM talla;
SELECT * FROM categoria;
